<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240202231000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, currency_code VARCHAR(3) NOT NULL, currency_name VARCHAR(255) NOT NULL, currency_symbol VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql("INSERT INTO `currency` (`id`, `currency_code`, `currency_name`, `currency_symbol`) VALUES
    (1, 'AFA', 'Afghan Afghani', '؋'),
(2, 'ALL', 'Albanian Lek', 'Lek'),
(3, 'DZD', 'Algerian Dinar', 'دج'),
(4, 'AOA', 'Angolan Kwanza', 'Kz'),
(5, 'ARS', 'Argentine Peso', '$'),
(6, 'AMD', 'Armenian Dram', '֏'),
(7, 'AWG', 'Aruban Florin', 'ƒ'),
(8, 'AUD', 'Australian Dollar', '$'),
(9, 'AZN', 'Azerbaijani Manat', 'm'),
(10, 'BSD', 'Bahamian Dollar', 'B$'),
(11, 'BHD', 'Bahraini Dinar', '.د.ب'),
(12, 'BDT', 'Bangladeshi Taka', '৳'),
(13, 'BBD', 'Barbadian Dollar', 'Bds$'),
(14, 'BYR', 'Belarusian Ruble', 'Br'),
(15, 'BEF', 'Belgian Franc', 'fr'),
(16, 'BZD', 'Belize Dollar', '$'),
(17, 'BMD', 'Bermudan Dollar', '$'),
(18, 'BTN', 'Bhutanese Ngultrum', 'Nu.'),
(19, 'BTC', 'Bitcoin', '฿'),
(20, 'BOB', 'Bolivian Boliviano', 'Bs.'),
(21, 'BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM'),
(22, 'BWP', 'Botswanan Pula', 'P'),
(23, 'BRL', 'Brazilian Real', 'R$'),
(24, 'GBP', 'British Pound Sterling', '£'),
(25, 'BND', 'Brunei Dollar', 'B$'),
(26, 'BGN', 'Bulgarian Lev', 'Лв.'),
(27, 'BIF', 'Burundian Franc', 'FBu'),
(28, 'KHR', 'Cambodian Riel', 'KHR'),
(29, 'CAD', 'Canadian Dollar', '$'),
(30, 'CVE', 'Cape Verdean Escudo', '$'),
(31, 'KYD', 'Cayman Islands Dollar', '$'),
(32, 'XOF', 'CFA Franc BCEAO', 'CFA'),
(33, 'XAF', 'CFA Franc BEAC', 'FCFA'),
(34, 'XPF', 'CFP Franc', '₣'),
(35, 'CLP', 'Chilean Peso', '$'),
(36, 'CLF', 'Chilean Unit of Account', 'CLF'),
(37, 'CNY', 'Chinese Yuan', '¥'),
(38, 'COP', 'Colombian Peso', '$'),
(39, 'KMF', 'Comorian Franc', 'CF'),
(40, 'CDF', 'Congolese Franc', 'FC'),
(41, 'CRC', 'Costa Rican Colón', '₡'),
(42, 'HRK', 'Croatian Kuna', 'kn'),
(43, 'CUC', 'Cuban Convertible Peso', '$, CUC'),
(44, 'CZK', 'Czech Republic Koruna', 'Kč'),
(45, 'DKK', 'Danish Krone', 'Kr.'),
(46, 'DJF', 'Djiboutian Franc', 'Fdj'),
(47, 'DOP', 'Dominican Peso', '$'),
(48, 'XCD', 'East Caribbean Dollar', '$'),
(49, 'EGP', 'Egyptian Pound', 'ج.م'),
(50, 'ERN', 'Eritrean Nakfa', 'Nfk'),
(51, 'EEK', 'Estonian Kroon', 'kr'),
(52, 'ETB', 'Ethiopian Birr', 'Nkf'),
(53, 'EUR', 'Euro', '€'),
(54, 'FKP', 'Falkland Islands Pound', '£'),
(55, 'FJD', 'Fijian Dollar', 'FJ$'),
(56, 'GMD', 'Gambian Dalasi', 'D'),
(57, 'GEL', 'Georgian Lari', 'ლ'),
(58, 'DEM', 'German Mark', 'DM'),
(59, 'GHS', 'Ghanaian Cedi', 'GH₵'),
(60, 'GIP', 'Gibraltar Pound', '£'),
(61, 'GRD', 'Greek Drachma', '₯, Δρχ, Δρ'),
(62, 'GTQ', 'Guatemalan Quetzal', 'Q'),
(63, 'GNF', 'Guinean Franc', 'FG'),
(64, 'GYD', 'Guyanaese Dollar', '$'),
(65, 'HTG', 'Haitian Gourde', 'G'),
(66, 'HNL', 'Honduran Lempira', 'L'),
(67, 'HKD', 'Hong Kong Dollar', '$'),
(68, 'HUF', 'Hungarian Forint', 'Ft'),
(69, 'ISK', 'Icelandic Króna', 'kr'),
(70, 'INR', 'Indian Rupee', '₹'),
(71, 'IDR', 'Indonesian Rupiah', 'Rp'),
(72, 'IRR', 'Iranian Rial', '﷼'),
(73, 'IQD', 'Iraqi Dinar', 'د.ع'),
(74, 'ILS', 'Israeli New Sheqel', '₪'),
(75, 'ITL', 'Italian Lira', 'L,£'),
(76, 'JMD', 'Jamaican Dollar', 'J$'),
(77, 'JPY', 'Japanese Yen', '¥'),
(78, 'JOD', 'Jordanian Dinar', 'ا.د'),
(79, 'KZT', 'Kazakhstani Tenge', 'лв'),
(80, 'KES', 'Kenyan Shilling', 'KSh'),
(81, 'KWD', 'Kuwaiti Dinar', 'ك.د'),
(82, 'KGS', 'Kyrgystani Som', 'лв'),
(83, 'LAK', 'Laotian Kip', '₭'),
(84, 'LVL', 'Latvian Lats', 'Ls'),
(85, 'LBP', 'Lebanese Pound', '£'),
(86, 'LSL', 'Lesotho Loti', 'L'),
(87, 'LRD', 'Liberian Dollar', '$'),
(88, 'LYD', 'Libyan Dinar', 'د.ل'),
(89, 'LTC', 'Litecoin', 'Ł'),
(90, 'LTL', 'Lithuanian Litas', 'Lt'),
(91, 'MOP', 'Macanese Pataca', '$'),
(92, 'MKD', 'Macedonian Denar', 'ден'),
(93, 'MGA', 'Malagasy Ariary', 'Ar'),
(94, 'MWK', 'Malawian Kwacha', 'MK'),
(95, 'MYR', 'Malaysian Ringgit', 'RM'),
(96, 'MVR', 'Maldivian Rufiyaa', 'Rf'),
(97, 'MRO', 'Mauritanian Ouguiya', 'MRU'),
(98, 'MUR', 'Mauritian Rupee', '₨'),
(99, 'MXN', 'Mexican Peso', '$'),
(100, 'MDL', 'Moldovan Leu', 'L'),
(101, 'MNT', 'Mongolian Tugrik', '₮'),
(102, 'MAD', 'Moroccan Dirham', 'MAD'),
(103, 'MZM', 'Mozambican Metical', 'MT'),
(104, 'MMK', 'Myanmar Kyat', 'K'),
(105, 'NAD', 'Namibian Dollar', '$'),
(106, 'NPR', 'Nepalese Rupee', '₨'),
(107, 'ANG', 'Netherlands Antillean Guilder', 'ƒ'),
(108, 'TWD', 'New Taiwan Dollar', '$'),
(109, 'NZD', 'New Zealand Dollar', '$'),
(110, 'NIO', 'Nicaraguan Córdoba', 'C$'),
(111, 'NGN', 'Nigerian Naira', '₦'),
(112, 'KPW', 'North Korean Won', '₩'),
(113, 'NOK', 'Norwegian Krone', 'kr'),
(114, 'OMR', 'Omani Rial', '.ع.ر'),
(115, 'PKR', 'Pakistani Rupee', '₨'),
(116, 'PAB', 'Panamanian Balboa', 'B/.'),
(117, 'PGK', 'Papua New Guinean Kina', 'K'),
(118, 'PYG', 'Paraguayan Guarani', '₲'),
(119, 'PEN', 'Peruvian Nuevo Sol', 'S/.'),
(120, 'PHP', 'Philippine Peso', '₱'),
(121, 'PLN', 'Polish Zloty', 'zł'),
(122, 'QAR', 'Qatari Rial', 'ق.ر'),
(123, 'RON', 'Romanian Leu', 'lei'),
(124, 'RUB', 'Russian Ruble', '₽'),
(125, 'RWF', 'Rwandan Franc', 'FRw'),
(126, 'SVC', 'Salvadoran Colón', '₡'),
(127, 'WST', 'Samoan Tala', 'SAT'),
(128, 'STD', 'São Tomé and Príncipe Dobra', 'Db'),
(129, 'SAR', 'Saudi Riyal', '﷼'),
(130, 'RSD', 'Serbian Dinar', 'din'),
(131, 'SCR', 'Seychellois Rupee', 'SRe'),
(132, 'SLL', 'Sierra Leonean Leone', 'Le'),
(133, 'SGD', 'Singapore Dollar', '$'),
(134, 'SKK', 'Slovak Koruna', 'Sk'),
(135, 'SBD', 'Solomon Islands Dollar', 'Si$'),
(136, 'SOS', 'Somali Shilling', 'Sh.so.'),
(137, 'ZAR', 'South African Rand', 'R'),
(138, 'KRW', 'South Korean Won', '₩'),
(139, 'SSP', 'South Sudanese Pound', '£'),
(140, 'XDR', 'Special Drawing Rights', 'SDR'),
(141, 'LKR', 'Sri Lankan Rupee', 'Rs'),
(142, 'SHP', 'St. Helena Pound', '£'),
(143, 'SDG', 'Sudanese Pound', '.س.ج'),
(144, 'SRD', 'Surinamese Dollar', '$'),
(145, 'SZL', 'Swazi Lilangeni', 'E'),
(146, 'SEK', 'Swedish Krona', 'kr'),
(147, 'CHF', 'Swiss Franc', 'CHf'),
(148, 'SYP', 'Syrian Pound', 'LS'),
(149, 'TJS', 'Tajikistani Somoni', 'SM'),
(150, 'TZS', 'Tanzanian Shilling', 'TSh'),
(151, 'THB', 'Thai Baht', '฿'),
(152, 'TOP', 'Tongan Pa\'anga', '$'),
(153, 'TTD', 'Trinidad & Tobago Dollar', '$'),
(154, 'TND', 'Tunisian Dinar', 'ت.د'),
(155, 'TRY', 'Turkish Lira', '₺'),
(156, 'TMT', 'Turkmenistani Manat', 'T'),
(157, 'UGX', 'Ugandan Shilling', 'USh'),
(158, 'UAH', 'Ukrainian Hryvnia', '₴'),
(159, 'AED', 'United Arab Emirates Dirham', 'إ.د'),
(160, 'UYU', 'Uruguayan Peso', '$'),
(161, 'USD', 'US Dollar', '$'),
(162, 'UZS', 'Uzbekistan Som', 'лв'),
(163, 'VUV', 'Vanuatu Vatu', 'VT'),
(164, 'VEF', 'Venezuelan BolÃvar', 'Bs'),
(165, 'VND', 'Vietnamese Dong', '₫'),
(166, 'YER', 'Yemeni Rial', '﷼'),
(167, 'ZMK', 'Zambian Kwacha', 'ZK'),
(168, 'ZWL', 'Zimbabwean dollar', '$')");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE currency');
    }
}
